services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
